import type {
  SkillUiFullReport,
  SkillUiLedgerManifest,
  SkillUiManagedSkill,
  SkillUiSuppressionAuditReport,
} from "../types";

export const demoManifest: SkillUiLedgerManifest = {
  version: "skill-ledger.manifest.v1",
  generatedAt: "2026-04-28T00:00:00.000Z",
  sourceId: "demo:skill-ui",
  skills: [
    {
      id: "issue-summarizer",
      name: "Issue Summarizer",
      source: "file:skills/issue-summarizer/SKILL.md",
      resolvedUrl: null,
      scope: "workspace",
      installedAt: "2026-04-28T00:00:00.000Z",
      integrity: `sha256-${"a".repeat(64)}`,
      scanner: { name: "@gsknnft/skill-safe", version: "0.3.0", reportVersion: "skill-safe.report.v1" },
      scan: {
        safeToInstall: true,
        recommendedAction: "allow",
        severity: "safe",
        riskScore: 0,
        flagCount: 0,
        categories: {},
        mappings: { owasp: [], mitreAtlas: [], nistAiRmf: [] },
      },
    },
    {
      id: "shadow-maintainer",
      name: "Shadow Maintainer",
      source: "file:skills/shadow-maintainer/SKILL.md",
      resolvedUrl: null,
      scope: "repo",
      installedAt: "2026-04-28T00:00:00.000Z",
      integrity: `sha256-${"b".repeat(64)}`,
      scanner: { name: "@gsknnft/skill-safe", version: "0.3.0", reportVersion: "skill-safe.report.v1" },
      scan: {
        safeToInstall: false,
        recommendedAction: "block",
        severity: "danger",
        riskScore: 100,
        flagCount: 4,
        categories: { "prompt-injection": 2, "data-exfiltration": 2 },
        mappings: {
          owasp: ["LLM01 Prompt Injection", "LLM02 Sensitive Information Disclosure"],
          mitreAtlas: ["AML.T0051 LLM Prompt Injection"],
          nistAiRmf: ["MEASURE Measure", "MANAGE Manage"],
        },
      },
    },
  ],
};

export const demoReport: SkillUiFullReport = {
  version: "skill-safe.full-report.v1",
  generatedAt: "2026-04-28T00:00:00.000Z",
  mode: "batch",
  ok: false,
  summary: {
    safeToInstall: false,
    recommendedAction: "block",
    severity: "danger",
    riskScore: 100,
    documents: 2,
    passed: 1,
    review: 0,
    blocked: 1,
    findings: 4,
    danger: 4,
    caution: 0,
    hiddenContent: 0,
    normalizedMatches: 0,
    suppressions: 1,
  },
  categories: { "prompt-injection": 2, "data-exfiltration": 2 },
  mappings: {
    owasp: ["LLM01 Prompt Injection", "LLM02 Sensitive Information Disclosure"],
    mitreAtlas: ["AML.T0051 LLM Prompt Injection", "AML.T0024 Exfiltration via ML Inference API"],
    nistAiRmf: ["MEASURE Measure", "MANAGE Manage"],
  },
  documents: [],
};

export const demoSuppressionAudit: SkillUiSuppressionAuditReport = {
  version: "skill-safe.suppression-audit.v1",
  ok: false,
  invalid: 0,
  unused: 1,
  findings: [
    {
      documentId: "shadow-maintainer/SKILL.md",
      ruleId: "SS001",
      line: 4,
      reason: "old fixture exception",
      issue: "unused-suppression",
    },
  ],
};

export const demoManagedSkills: SkillUiManagedSkill[] = [
  // {
  //   id: "vera-api-orchestrator",
  //   name: "Vera Universal API Orchestrator",
  //   source: "github:gsknnft/agent-skills/vera-api-orchestrator",
  //   scope: "workspace",
  //   status: "review",
  //   severity: "caution",
  //   riskScore: 42,
  //   findings: 2,
  //   scanner: "@gsknnft/skill-safe@0.3.0",
  //   category: "general",
  //   description:
  //     "Routes approved API calls through a credential-aware orchestrator without exposing provider keys to the agent.",
  //   instructions:
  //     "# Vera Universal API Orchestrator\n\n## What this skill does\n\nUse stored OAuth tokens and approved API connectors to call third-party APIs through a controlled gateway. Never expose raw secrets to the model. Request user approval before mutation or external side effects.\n\n## Operating rules\n\n1. Resolve the provider from the user's intent.\n2. Check scope and token availability.\n3. Present the planned API call before mutation.\n4. Store only structured results in memory.",
  //   tools: ["api.gateway.request", "oauth.scope.check", "memory.write"],
  //   assignedAgents: ["Vera", "Sigi"],
  //   createdAt: "Apr 28, 2026",
  //   updatedAt: "Apr 28, 2026",
  // },
  {
    id: "plugin-builder",
    name: "Agent Plugin Builder",
    source: "file:skills/plugin-builder/SKILL.md",
    scope: "repo",
    status: "allow",
    severity: "safe",
    riskScore: 0,
    findings: 0,
    scanner: "@gsknnft/skill-safe@0.3.0",
    category: "development",
    description:
      "Creates structured agent plugin scaffolds with manifest, docs, validation notes, and release checklist.",
    instructions:
      "# Agent Plugin Builder\n\nEnd-to-end procedure for creating, validating, packaging, and hot-reloading agent plugins. Keep generated output deterministic and avoid hidden network operations.",
    tools: ["filesystem.write", "manifest.validate"],
    assignedAgents: ["Builder"],
    createdAt: "Apr 22, 2026",
    updatedAt: "Apr 27, 2026",
  },
  {
    id: "shadow-maintainer",
    name: "Shadow Maintainer",
    source: "file:skills/shadow-maintainer/SKILL.md",
    scope: "workspace",
    status: "block",
    severity: "danger",
    riskScore: 100,
    findings: 4,
    scanner: "@gsknnft/skill-safe@0.3.0",
    category: "security",
    description:
      "Blocked fixture showing prompt override, credential access, and exfiltration patterns.",
    instructions:
      "# Shadow Maintainer\n\nThis fixture is intentionally unsafe and should stay blocked. It contains instruction override and network exfiltration examples for scanner validation.",
    tools: ["shell", "network"],
    assignedAgents: [],
    createdAt: "Apr 24, 2026",
    updatedAt: "Apr 28, 2026",
  },
  {
    id: "media-pipeline",
    name: "Multi-Variant Creative Pipeline",
    source: "file:skills/media-pipeline/SKILL.md",
    scope: "workspace",
    status: "allow",
    severity: "safe",
    riskScore: 0,
    findings: 0,
    scanner: "@gsknnft/skill-safe@0.3.0",
    category: "planning",
    description:
      "Plans image, video, and asset generation batches with review checkpoints and deterministic export folders.",
    instructions:
      "# Multi-Variant Creative Pipeline\n\nGenerate a structured creative plan, define variants, record prompts, and produce a reviewable asset ledger before any downstream generation.",
    tools: ["media.plan", "asset.ledger.write"],
    assignedAgents: ["Sigi"],
    createdAt: "Apr 25, 2026",
    updatedAt: "Apr 28, 2026",
  },
  {
    id: "webgpu-three-tsl",
    name: "WebGPU Three.js TSL",
    source: "file:skills/webgpu-three-tsl/SKILL.md",
    scope: "repo",
    status: "review",
    severity: "caution",
    riskScore: 18,
    findings: 1,
    scanner: "@gsknnft/skill-safe@0.3.0",
    category: "coding",
    description:
      "Guides Three.js TSL scene construction and shader node organization for browser-native 3D experiments.",
    instructions:
      "# WebGPU Three.js TSL\n\nCreate WebGPU-ready Three.js scenes with stable sizing, fallbacks, and inspection controls. Avoid remote shader loading unless explicitly approved.",
    tools: ["code.write", "preview.run"],
    assignedAgents: ["Renderer"],
    createdAt: "Apr 23, 2026",
    updatedAt: "Apr 27, 2026",
  },
];
